# Generated by Django 5.1.4 on 2024-12-19 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='rand_id',
            field=models.TextField(blank=True, default='', null=True, unique=True, verbose_name='ID'),
        ),
    ]
