# Generated by Django 5.1.4 on 2024-12-19 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_message_rand_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='rand_id',
            field=models.TextField(blank=True, default='', null=True, verbose_name='ID'),
        ),
    ]
